CREATE DATABASE IF NOT EXISTS devDB;
USE devDB;

CREATE TABLE IF NOT EXISTS Course
(
    CourseId VARCHAR(255) NOT NULL,
    ClassCode VARCHAR(255) NOT NULL,
    CourseName VARCHAR(255) NOT NULL,
    Description VARCHAR(255),
    PRIMARY KEY (CourseId)
);

CREATE TABLE IF NOT EXISTS User
(
    UUID VARCHAR(255) NOT NULL,
    Role VARCHAR(255) NOT NULL,
    PRIMARY KEY (UUID)
);

CREATE TABLE IF NOT EXISTS Registration
(
    RegistrationId INTEGER NOT NULL AUTO_INCREMENTAL,
    CourseId VARCHAR(255) NOT NULL,
    UserId VARCHAR(255) NOT NULL,
    CONSTRAINT fk_course FOREIGN KEY (CourseId) REFERENCES Course(CourseId),
    CONSTRAINT fk_user FOREIGN KEY (UserId) REFERENCES User(UUID),
    PRIMARY KEY (RegistrationId)
);

CREATE TABLE IF NOT EXISTS Schedule
(
    ScheduleId INTEGER NOT NULL AUTO_INCREMENTAL,
    CourseId VARCHAR(255) NOT NULL,
    Day VARCHAR(255) NOT NULL,
    StartTime TIME NOT NULL,
    EndTime TIME NOT NULL,
    CONSTRAINT fk_course FOREIGN KEY (CourseId) REFERENCES Course(CourseId),
    PRIMARY KEY (ScheduleId)
);